#!/bin/sh -xe
BASE_DIR=$(cd $(dirname $0) && pwd)/../
cd $BASE_DIR
# copy template files
cp src/template/notebooks/template.ipynb interaction/template.ipynb
cp src/template/data/template.csv interaction/data/template_data.csv

docker run --rm -p 10001:8888 -v "$PWD"/interaction:/home/jovyan/work floweaver_docker/base
